name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r quant_backend/requirements.txt
          pip install pytest pytest-cov flask-socketio
      - name: Run tests
        run: |
          PYTHONPATH=. pytest --maxfail=1 --disable-warnings --tb=short 